"""Taqsim is a water-modelling and rule-authoring layer over incidence."""

from .basin import (
    Basin,
    BasinRun,
    BuiltBasin,
    Presence,
    Reach,
    Resolution,
    RuleParameter,
    Sink,
    Source,
    TimeAxis,
    WaterSeries,
    WaterValue,
    WaterValues,
)
from .docs import get_docs_path
from .optimization import (
    BasinObjective,
    BasinOptimizeResult,
    BasinSolution,
    optimize_basin,
)
from .persistence import (
    IncidenceVersionMismatchError,
    SavedRunError,
    SavedRunFormatError,
    incidence_version,
    load_run,
    save_run,
)
from .vocabulary import (
    CanalLosses,
    CanalLossRule,
    EFlowSplit,
    EFlowSplitPolicy,
    EvaporationLossRule,
    MonthlyDistribution,
    Parameter,
    PriorityDistribution,
    ReservoirEvaporation,
    ZoneRelease,
    ZoneReleasePolicy,
    monthly_parameters,
)

__all__ = [
    "Basin",
    "BasinRun",
    "BuiltBasin",
    "Presence",
    "Reach",
    "Resolution",
    "RuleParameter",
    "Sink",
    "Source",
    "TimeAxis",
    "WaterSeries",
    "WaterValue",
    "WaterValues",
    "Parameter",
    "monthly_parameters",
    "ZoneRelease",
    "ZoneReleasePolicy",
    "MonthlyDistribution",
    "PriorityDistribution",
    "EFlowSplit",
    "EFlowSplitPolicy",
    "ReservoirEvaporation",
    "EvaporationLossRule",
    "CanalLosses",
    "CanalLossRule",
    "save_run",
    "load_run",
    "incidence_version",
    "SavedRunError",
    "SavedRunFormatError",
    "IncidenceVersionMismatchError",
    "BasinObjective",
    "BasinOptimizeResult",
    "BasinSolution",
    "optimize_basin",
    "get_docs_path",
]

__version__ = "0.1.4"
