"""Taqsim is a water-modelling and rule-authoring layer over incidence."""

from .docs import get_docs_path
from .inputs import (
    CanalSeepageCoefficient,
    IntervalMeanRate,
    IntervalVolume,
    Length,
    SourceProvenance,
    SurfaceArea,
    VolumetricRate,
    WaterDepth,
    WaterVolume,
)
from .optimization import (
    WaterSystemObjective,
    WaterSystemOptimizeResult,
    WaterSystemSolution,
    optimize_water_system,
)
from .persistence import (
    IncidenceVersionMismatchError,
    SavedRunError,
    SavedRunFormatError,
    incidence_version,
    load_run,
    save_run,
)
from .vocabulary import (
    CanalLosses,
    CanalLossRule,
    EFlowSplit,
    EFlowSplitPolicy,
    EvaporationLossRule,
    MonthlyDistribution,
    Parameter,
    PriorityDistribution,
    ReservoirEvaporation,
    ZoneRelease,
    ZoneReleasePolicy,
    monthly_parameters,
)
from .water_system import (
    BuiltWaterSystem,
    ConservationQuantum,
    Presence,
    Reach,
    RuleParameter,
    Sink,
    Source,
    TimeAxis,
    WaterSeries,
    WaterSystem,
    WaterSystemRun,
    WaterValue,
    WaterValues,
)

__all__ = [
    "WaterSystem",
    "WaterSystemRun",
    "BuiltWaterSystem",
    "Presence",
    "Reach",
    "ConservationQuantum",
    "RuleParameter",
    "Sink",
    "Source",
    "TimeAxis",
    "WaterSeries",
    "WaterValue",
    "WaterValues",
    "IntervalVolume",
    "IntervalMeanRate",
    "SourceProvenance",
    "WaterVolume",
    "VolumetricRate",
    "WaterDepth",
    "Length",
    "SurfaceArea",
    "CanalSeepageCoefficient",
    "Parameter",
    "monthly_parameters",
    "ZoneRelease",
    "ZoneReleasePolicy",
    "MonthlyDistribution",
    "PriorityDistribution",
    "EFlowSplit",
    "EFlowSplitPolicy",
    "ReservoirEvaporation",
    "EvaporationLossRule",
    "CanalLosses",
    "CanalLossRule",
    "save_run",
    "load_run",
    "incidence_version",
    "SavedRunError",
    "SavedRunFormatError",
    "IncidenceVersionMismatchError",
    "WaterSystemObjective",
    "WaterSystemOptimizeResult",
    "WaterSystemSolution",
    "optimize_water_system",
    "get_docs_path",
]

__version__ = "0.1.4"
